### ISSUE TITLE
Feature: Docker compose support

### ISSUE THREAD

**Issue by poudenes** [pashword/pashword#15]
Hi There,

When will there be a docker compose support?

Im running now from a other user, would be nice to have it from the developer itself!

**Comment by NayamAmarshe** [comment]
Well I'm late, sorry. Just added a compose file :)

**Comment by NayamAmarshe** [comment]
https://hub.docker.com/r/nayamamarshe/pashword

**Comment by poudenes** [comment]
Wanna update now get this error:

pashword  | 2026-09-16T08:49:38.657933857Z exec /usr/local/bin/docker-entrypoint.sh: exec format error
pashword  | 2026-09-16T08:49:39.133973711Z exec /usr/local/bin/docker-entrypoint.sh: exec format error
pashword  | 2026-09-16T08:49:39.633804901Z exec /usr/local/bin/docker-entrypoint.sh: exec format error
pashword  | 2026-09-16T08:49:40.277300479Z exec /usr/local/bin/docker-entrypoint.sh: exec format error
pashword  | 2026-09-16T08:49:41.304845641Z exec /usr/local/bin/docker-entrypoint.sh: exec format error
pashword  | 2026-09-16T08:49:43.146485628Z exec /usr/local/bin/docker-entrypoint.sh: exec format error
pashword  | 2026-09-16T08:49:46.581399392Z exec /usr/local/bin/docker-entrypoint.sh: exec format error
pashword  | 2026-09-16T08:49:53.229212329Z exec /usr/local/bin/docker-entrypoint.sh: exec format error
