### ISSUE TITLE
Request: Add ip:port to website part

### ISSUE THREAD

**Issue by poudenes** [pashword/pashword#7]
First of all GREAT CODE !!!

Would be nice to able to add ip:port to website part.
I have many docker application accessible from http://ip:port

Now I can't add this into the website part. So I have to give a "fake" website to make a secret key.

Cheers,
Peter

**Comment by NayamAmarshe** [comment]
Thanks for the idea! I guess I can allow `:` character in the website input :)

**Comment by poudenes** [comment]
Hi, any idea when you will implement this :)?

**Comment by NayamAmarshe** [comment]
> Hi, any idea when you will implement this :)?

Ah very sorry. I got really busy with other work and projects. I'll get it done before tomorrow.

**Comment by NayamAmarshe** [comment]
@poudenes I've updated the code to allow ports, please let me know if I missed something and very sorry for all the delay.

**Comment by poudenes** [comment]
Updated and working!! Thanks!
