### ISSUE TITLE
Question: How handle hacked websites

### ISSUE THREAD

**Issue by poudenes** [pashword/pashword#8]
Hi All,

Again GREAT CODE !!! Im using it now, changed all my normal passwords and almost I can delete my password app.
But what happen when a website is hacked and you need to give a new password. Then you have to remember a second secret key just for that website.

So when you want change it you have always enter this second secret key. Will there be a solution for?
A option check that a site was hacked so you enter all your old information but with this "was hacked" option that you can turn on the Pashword will be different then the first one. Always different and same, there is a extra character added into the generator to create the Pashword.

Its just a question how we can tackle this for the future :)

**Comment by poudenes** [comment]
I was reading the Q&A and its already there. So only the option to point that a site is hacked will give you a easier way remember 1 secret key

**Comment by NayamAmarshe** [comment]
> But what happen when a website is hacked and you need to give a new password. Then you have to remember a second secret key just for that website.

I personally use Pashword with my browser's password manager. This way, my browser can remember what sites I am on, what my secret key is and I can use Pashword even without the browser sync. 

You're right about remembering 2 secret keys, IF you keep using the old key along with a new one. The suggested method is to change your secret key for all your accounts after a breach, this way you can ensure maximum protection and still need to remember just one secret key.

There are no perfect solutions to the problem, it's just one limitation that comes with the concept of hashed passwords but I personally am not too worried about it as data breaches are very rare and will still not be able to let hackers access my other accounts :) So it may be a little more inconvenient but it's still better than not having Pashword at all :)

**Comment by NayamAmarshe** [comment]
That's a very good idea as well :D

**Comment by NayamAmarshe** [comment]
Also @poudenes you could use my other project [MagLit](https://maglit.me) to create a link with your secret keys and password protect it maybe ;) So that when you need your secret keys, it's only you who can access them and remembering a link is pretty easy too :)

**Comment by poudenes** [comment]
I use cloud flare. All my subdomains are using cloud flare tunnel so my external IP is unknown.
But its a nice tool as well
